# Generated by Django 3.1.3 on 2020-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='soundcloud_track_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='soundcloud_track_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.BinaryField(blank=True),
        ),
    ]
